const daysInMonth = 30;
let hoursInMonth = daysInMonth * 24;
let minutesInMonth = hoursInMonth * 60;
console.log(daysInMonth, hoursInMonth, minutesInMonth);
console.log("================================================");
let health = 100;
let energy = 100;
health = health - 10;
energy = energy - 10;
console.log(health, energy);
console.log("================================================");
let totalPrice = 500;
let discountedPrice = (totalPrice / 100) * 10;
console.log(discountedPrice);
console.log("================================================");
const floatNumber = 12.78;
console.log(Math.floor(floatNumber));
console.log("================================================");
const floatString = "45.67";
let parsedFloat = parseFloat(floatString);
console.log(parsedFloat);
console.log("================================================");
const intString = "123";
let parsedInt = parseInt(intString);
console.log(parsedInt);
console.log("================================================");
let sqrtNum = 11;
let sqrtNumber = Math.sqrt(sqrtNum);
console.log(sqrtNumber);
console.log("================================================");
const integer = 42;
const stringNumber = "256";
let convertedInt = parseInt(stringNumber);
console.log(convertedInt);
let convertedString = integer.toString();
console.log(convertedString);
