let result;
result = 5 + 5 + `5`;
console.log(result);
console.log("================================================");
email = "test@gmail.com";
console.log(email.includes("@"));
console.log(email.length);
console.log("================================================");
test = "My";
test2 = "name";
test3 = "is";
let fullName = test + test2 + test3 + " Viktor";
console.log(fullName);
console.log("================================================");
let userName = "Абоба";
let payment = 11;
console.log(`Карочи ${userName} ты мне должен ${payment} гривен`);
console.log("================================================");
